name: hongpra
description: A new Flutter application.

publish_to:

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  firebase_auth: ^0.18.0+1
  cloud_firestore: "^0.14.0+2"
  firebase_core: "0.5.0"
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  device_preview:
  scroll_app_bar:
#  carousel_slider:
  carousel_pro:
  page_transition:
  photo_view:
#  full_screen_image:
  flutter_barcode_scanner:
  pull_to_refresh:


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/amulet1.jpg
    - assets/images/certificate1.jpg
    - assets/images/notfound.png

  fonts:
    - family: Srisakdi
      fonts:
      - asset: fonts/Srisakdi/Srisakdi-Regular.ttf
      - asset: fonts/Srisakdi/Srisakdi-Bold.ttf
    - family: EkkamaiNew
      fonts:
      - asset: fonts/EkkamaiNew/EkkamaiNew-Regular.ttf
    - family: Prompt
      fonts:
      - asset: fonts/Prompt/Prompt-Regular.ttf
      - asset: fonts/Prompt/Prompt-Bold.ttf

