name: hongpra
description: A new Flutter application.

publish_to:

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  firebase_auth: ^0.18.0+1
  cloud_firestore: "^0.14.0+2"
  firebase_core: "0.5.0"
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  splashscreen: any
#----- Custom Libs
#-- Images
  photo_view:
  carousel_slider:
  carousel_pro:
#  full_screen_image:
#-- QR Code
  flutter_barcode_scanner:
  qr_flutter:
#-- Loading Effect
  pull_to_refresh:
#  loading:
  flutter_easyloading:
#-- Others
  device_preview:
#  scroll_app_bar:
  page_transition:
#  flutter_search_bar:



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons:

flutter:

  uses-material-design: true

  assets:
    - assets/images/notfound.png
    - assets/images/logo-0.jpg
    - assets/images/logo-1.jpg

  fonts:
    - family: Srisakdi
      fonts:
      - asset: fonts/Srisakdi/Srisakdi-Regular.ttf
      - asset: fonts/Srisakdi/Srisakdi-Bold.ttf
    - family: EkkamaiNew
      fonts:
      - asset: fonts/EkkamaiNew/EkkamaiNew-Regular.ttf
    - family: Prompt
      fonts:
      - asset: fonts/Prompt/Prompt-Regular.ttf
      - asset: fonts/Prompt/Prompt-Bold.ttf

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo-0.jpg"